version: '3.7'

services:

  nginx:
    image: nginx:alpine
    ports:
     - "8080:8080"
    volumes:
     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
     - ./services:/var/www/vhosts
    depends_on:
      - "app"

  app:
     image: php:7.4-fpm-alpine
     ports:
       - "9000:9000"
     volumes:
       - ./services:/var/www/vhosts
     working_dir: /var/www/vhosts
     environment:
       - ENV=development
       - API_KEY=C6E84D247E2D81B5B45D6D2D229D9
